version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    env_file: 
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: .
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  db_data:
